default_settings: null
behaviors:
  PelletGrabber:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 327680 
      learning_rate: 0.00005
      beta: 0.0042
      epsilon: 0.14
      lambd: 0.95
      num_epoch: 10
      shared_critic: false
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.995  
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 64
          num_layers: 3
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.01  # Balance intrinsic reward influence
        network_settings:
          normalize: true
          hidden_units: 64  # Larger network for curiosity
          num_layers: 3
    init_path: null
    keep_checkpoints: 20
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: C:\Unity Projects\Github\ml-agents\MlAgentsBuild\UnityEnvironment.exe
  env_args: null
  base_port: 6000
  num_envs: 57
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 5
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 30.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters: null
checkpoint_settings:
  run_id: pelletgrabber
  initialize_from: null
  load_model: true
  resume: true
  force: true
  train_model: true
  inference: false
  results_dir: results
torch_settings:
  device: cuda
debug: false
